# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      ENVIRONMENT: development
      DEBUG: "true"
    volumes:
      - ./backend:/app
      - ./logs/backend:/app/logs
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]